# Generated by Django 4.2.13 on 2024-09-25 18:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_activity_teams_players_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='token',
            field=models.UUIDField(default=uuid.UUID('5205f311-27b2-45f5-ac4b-4d1dd459c2cf'), null=True),
        ),
    ]
