# Generated by Django 4.2.13 on 2024-09-28 10:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_activity_creator_alter_teams_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='badges',
            name='active',
            field=models.CharField(default=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='token',
            field=models.UUIDField(default=uuid.UUID('293ae246-47c9-4e9d-855f-79d7dff946c2'), null=True),
        ),
    ]
