# Generated by Django 4.2.13 on 2024-10-12 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0011_alter_slots_active'),
        ('bookings', '0004_remove_booking_venue_booking_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='slot',
        ),
        migrations.AddField(
            model_name='bookingslots',
            name='slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot_bookings', to='vendor.slots'),
        ),
    ]
