# Generated by Django 4.2.13 on 2024-10-14 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0011_alter_slots_active'),
        ('bookings', '0005_remove_booking_slot_bookingslots_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venue_bookings', to='vendor.venue'),
        ),
    ]
